version: "3.9"
services:
  ops:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-om
    container_name: ops
    deploy:
      resources:
        limits:
          cpus: '2.000'
          memory: 8G
        reservations:
          cpus: '1.000'
          memory: 4G
    hostname: ops.om.internal
    networks:
      main:
        aliases:
          - ops
          - ops.om.internal
          - ops.alt.internal
    privileged: true
    ports:
      - "8080:8080"
      - "8443:8443"
      - "25999:25999"
      - "27700-27719:27700-27719"
    volumes:
      - ./certs:/certs

  node1:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: node1
    deploy:
      resources:
        limits:
          cpus: '2.000'
          memory: 2.5G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: node1.om.internal
    networks:
      main:
        aliases:
          - node1.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs
    ports: 
      - "27017:27171"

  node2:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: node2
    deploy:
      resources:
        limits:
          cpus: '2.000'
          memory: 2.5G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: node2.om.internal
    networks:
      main:
        aliases:
          - node2.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs
    ports: 
      - "27017:27172"

  node3:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: node3
    deploy:
      resources:
        limits:
          cpus: '2.000'
          memory: 2.5G
        reservations:
          cpus: '0.500'
          memory: 1G
    hostname: node3.om.internal
    networks:
      main:
        aliases:
          - node3.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs
    ports: 
      - "27017:27173"

  metadata:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: metadata
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.50G
        reservations:
          cpus: '0.333'
          memory: 0.333G
    hostname: metadata.om.internal
    networks:
      main:
        aliases:
          - metadata
          - metadata.om.internal
          - metadata.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  oplog:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: oplog
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.50G
        reservations:
          cpus: '0.333'
          memory: 0.33G
    hostname: oplog.om.internal
    networks:
      main:
        aliases:
          - oplog
          - oplog.om.internal
          - oplog.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  blockstore:
    build:
      context: .
      dockerfile: ./build/Dockerfile-aarch64-rhel8-node
    container_name: blockstore
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.50G
        reservations:
          cpus: '0.333'
          memory: 0.33G
    hostname: blockstore.om.internal
    networks:
      main:
        aliases:
          - blockstore
          - blockstore.om.internal
          - blockstore.alt.internal
    privileged: true
    volumes:
      - ./mongodb-mms:/etc/mongodb-mms:ro
      - ./certs:/certs

  proxy:
    image: diouxx/squid
    networks:
      main:
        aliases:
          - proxy
          - proxy.om.internal
          - proxy.alt.internal
    container_name: proxy
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 0.25G
        reservations:
          cpus: '0.125'
          memory: 0.125G
    hostname: proxy.om.internal
    ports:
      - "3128:3128"
    restart: always

  lb:
    build:
      context: .
      dockerfile: ./build/Dockerfile-nginx-lb
    networks:
      main: 
        aliases:
         - lb
         - lb.om.internal
         - lb.alt.internal
    container_name: lb
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 0.125G
        reservations:
          cpus: '0.125'
          memory: 0.062G
    ports: 
      - "80:80"
    restart: always

  smtp:
    image: dockage/mailcatcher:0.9.0
    networks:
      main: 
        aliases:
         - smtp
         - smtp.om.internal
         - smtp.alt.internal
    container_name: smtp
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 0.125G
        reservations:
          cpus: '0.125'
          memory: 0.062G
    ports: 
      - "1025:1025"
      - "1080:1080"
    restart: on-failure

  s3:
    image: dxflrs/garage:v1.0.0
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
    networks:
      main:
        aliases:
         - s3
         - s3.om.internal
         - oplog.s3.om.internal
         - blockstore.s3.om.internal
    container_name: s3
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 0.250G
        reservations:
          cpus: '0.250'
          memory: 0.250G
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
      - "3904:3904"

networks:
  main:
